### ISSUE TITLE
Notebook with theft deterrent server 4.0

### ISSUE THREAD

**Issue by ahmedkamel987654** [3ll34ndr0/desbloqueoNetbooks#1]
my brothers laptop is notebook with theft deterrent server 4.0 can you make something for this can he be opened or no Thank you very much if you answered

**Comment by 3ll34ndr0** [comment]
Hi! This software is for admins, sorry I can't do anything for your notebook's brother.

**Comment by marcos476** [comment]
Hola me pueden conseguir el codigo de desbloqueo de mi netbook del gobierno si les doy los datos?

**Comment by 3ll34ndr0** [comment]
Hola Marcos, no. Este es un software que no sirve de nada si el servidor de la institución no está funcionando. Sólo le sirve a quienes administran los sistemas.
