### ISSUE TITLE
No logro hacerlo correr

### ISSUE THREAD

**Issue by igniparra** [3ll34ndr0/desbloqueoNetbooks#2]
Hola Leandro! Me explicas como ejecutas esto? me parece que me falta una parte...

**Comment by 3ll34ndr0** [comment]
Hola! Esto es una automatización de lo que haría unx administradorx en la institución, que tiene acceso al sistema. No sirve para desbloquear si no está corriendo ese sistema, que es aparte. Vos tenés acceso a las credenciales de admin?
